### ISSUE TITLE
which branch?

### ISSUE THREAD

**Issue by spyhunter99** [TrilogisIT/WorldWind_Android#8]
Which branch is actually buildable? Master doesn't have any build scripts. The Kedzie branch is maven based but doesn't build (even after building the rajawali3d and adjusting the version numbers)

**Comment by ndorigatti** [comment]
Hello, the branches has been pushed when Eclipse ADT was still 'supported' and active so that's the way to build the app.
The WorldWind_Android is an android project that is a dependency of the "Sample App" project.
The fao-master and keidze master are the newest one. I have some merging on my pc but i was not able to push because of a lot of issues.
If the keidze branch can't build using eclipse, try to clean a bit the errors in the sample app, maybe there is something missing (the branch comes from another user pull request).

**Comment by spyhunter99** [comment]
Thanks for the reply. Is the app in the play store built with FAO or Keidze branch?

**Comment by ndorigatti** [comment]
The app in the play store is the master branch at the release 1.03, you can find it here: https://github.com/TrilogisIT/WorldWind_Android/tree/1.0.3
